TestDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dogs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/', include('carro.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from .import views

app_name="carro"

urlpatterns=[

    path("agregar/<int:producto_id>/" , views.agregar_producto, name='agregar'),
    path("eliminar/<int:producto_id>/" , views.eliminar_producto, name='eliminar'),
    path("restar/<int:producto_id>/" , views.restar_producto, name='restar'),
    path("limpiar/" , views.limpiar_carro, name='limpiar'),
]

dogs/urls.py
from django.urls import path, include
from .views import *
from . import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register('producto', ProductoViewset)


urlpatterns=[
    path('', index,name="Inicio"),
    
    path('quienessomos/', quienes, name='QuienesSomos'),

    path('galeria/', galeria, name='Galeria'),

    path('contactanos/', contacto, name='Contactanos'),

    path('agregar-producto/', agregar_producto, name="agregar_producto"),

    #path('listar-producto/', listarpreducto, name="listar_producto"),

    path('modificar-producto/<id>/', modificarproducto, name="modificar_productos"),

    path('registro/', registro,name="registro"),
    path('api/', include(router.urls)),
    path('tienda/', tienda,name="Tienda")




   
    
]

carro/models.py
from django.db import models

# Create your models here.

dogs/models.py
from django.db import models

# Create your models here.


class producto(models.Model):
    nombre= models.CharField(max_length=50)
    precio= models.IntegerField()
    descripcion= models.TextField()
    image=models.ImageField(upload_to="productos", null =True)
    def __str__(self):
        return self.nombre

opciones_consulta=[
    [0,"consulta"],
    [1,"solicitud producto"],
    [2,"sugerencia"],
    [3,"felicitaciones"] 
]

class Contacto(models.Model):
    nombre=models.CharField(max_length=50)
    correo=models.EmailField()
    tipo_consulta=models.IntegerField(choices=opciones_consulta)
    mensaje=models.TextField()
    avisos=models.BooleanField()
    def __str__(self):
        return self.nombre 

dogs/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError

class ContactoForm(forms.ModelForm):
  
    class Meta:
        model = Contacto
        fields = '__all__'


class ProductoForm(forms.ModelForm):
    nombre = forms.CharField(min_length=3, max_length=50)
    image = forms.ImageField(required=False)
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        existe = producto.objects.filter(nombre__iexact=nombre).exists()
        if existe:
            raise ValidationError("Este nombre ya existe")
        return nombre
    class Meta:
        model = producto
        fields = '__all__'
       
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from dogs.models import producto

# Create your views here.
def agregar_producto(requets, producto_id):

    carro=Carro(requets)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Tienda")

def eliminar_producto(requets, producto_id):

    carro=Carro(requets)
    producto=producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Tienda")

def restar_producto(requets, producto_id):

    carro=Carro(requets)
    producto=producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Tienda")

def limpiar_carro(requets, producto_id):

    carro=Carro(requets)
    carro.limpiar_carro()
    return redirect("Tienda")

dogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import*
from .forms import ContactoForm, ProductoForm, CustomUserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from rest_framework import viewsets
from .serializers import ProductoSerializer


# Create your views here.
class ProductoViewset(viewsets.ModelViewSet):
    queryset = producto.objects.all()
    serializer_class = ProductoSerializer

def index(request):
    return render(request, 'dogs/index.html')

def quienes(request):
    return render(request, 'dogs/quienessomos.html')

def galeria(request):
  
    return render(request, 'dogs/galeria.html')

def contacto(request):
    data = {
        'contacto': ContactoForm()
     }
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"]= "Solicitud Enviada"
        else:
            data["form"] = formulario

    return render(request, 'dogs/contactanos.html', data)


def agregar_producto(request):
    data = {
        'form': ProductoForm()
    }
    if request.method =='POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"]="Guardado Correctamente"
        
        
    return render(request, 'dogs/producto/agregar.html', data)

def listarpreducto(request):
    productos= producto.objects.all()

    data ={
        'productos': productos
    }
    return render(request, 'dogs/producto/lista.html', data)

def modificarproducto( request, id):
    
    producto = get_object_or_404(producto, id=id)

    data = {
        'form': ProductoForm(instance=producto) 
    }

    
    return render(request, 'dogs/producto/modificar.html', data)

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            return redirect(to="Inicio")
        data["form"] = formulario
    return render(request, 'registration/registro.html',data)

def tienda(request):
    productos = producto.objects.all()
    data={
        'productos': productos
    }
    return render(request, 'dogs/tienda.html',data)

dogs/templates/dogs/carro/widget.html
<table class="table table-bordered" style="color:black;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro Compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>

    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %} " class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %} " class="btn btn-sm btn-success">+</a>
                    </td>
                </tr>



            {%endfor%}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin Productos
                    </div>
                </td>
            </tr>
        {% endif %}

    </tbody>


</table>

dogs/templates/dogs/contactanos.html
<!DOCTYPE html>

<html>

<head>
    {% load static %}
    <title>Ingreso al sistema</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'dogs/css/contactanos.css'%}">

</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="#">
            <img src="{%static 'dogs/img/Logo.jpg'%}" width="100" height="100" alt="" />
        </a>
        <div class="collapse navbar-collapse" id="opciones">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link " href="/">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/quienessomos/">Quienes somos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/galeria/">Galeria</a>

                </li>
                   {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout'%}"> Cerrar Sesión</a>
                </li>
                {% else %}
                <li> <a href="{% url 'login' %} "> Iniciar Sesión </a></li>
                {% endif %}
             


            </ul>
        </div>
    </nav>
    <br>
    <br>
    

{% load crispy_forms_tags %}
<div class=" container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="car">
                <div class="car-body">
                    <h2> Contactanos</h2>
                    <hr>
                    <form action="" method="post">

                        {% csrf_token %} 
                        {{contacto| crispy}}
                        <a href="/">ir al home</a> |
                        
                        


                        <br>
                        <input type="submit" value="Enviar" class="btn btn-success float-right">
                    </form>
                    {{mensaje}}
                </div>

            </div>
        </div>
    </div>

<br>







<br>


    <div class="row">
        <div class="container">
            <footer class="bg-light text-center text-black">
                <div class="container p-4 pb-0">
                    <section class="mb-3">
                        <!--  facebook -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-facebook-f"><img src="{% static 'dogs/img/facebook.png'%}" width="30px"></i></a>
                        <!-- instagram -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-instagram"><img src="{% static 'dogs/img/logoinsta.png'%}" width="30px"></i></a>
                        <!-- twitter -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-twitter"><img src="{%static 'dogs/img/twitter-logo.png'%}" width="30px"></i></a>
                </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                    Cesar Gonzalez<br> © 2022 Copyright:
                </div>
            </footer>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>



</body>

</html>

dogs/templates/dogs/galeria.html
<!DOCTYPE html>


<html>

<head>
    {% load static %}
    
    <title>Galeria de Productos</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'dogs/css/galeria.css'%} " />
</head>

<body>

    <!-- esto es la barra de tareas -->
    <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="#">
            <img src="{%static 'dogs/img/Logo.jpg'%}" width="100" height="100" alt="" />
        </a>
        <div class="collapse navbar-collapse" id="opciones">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link " href="/">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/quienessomos/">Quienes Somos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contactanos/">Contactanos</a>

                </li>
                   {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout'%}"> Cerrar Sesión</a>
                </li>
                {% else %}
                <li> <a href="{% url 'login' %} "> Iniciar Sesión </a></li>
                {% endif %}


            </ul>
        </div>
    </nav>

    <div class="c-img ">
        <figure>
            <img src="{% static 'dogs/img/pet id.jfif'%} " alt=" ">
            <div class="texto ">
                <h2>Placa para su mascota
                    <p>
                        $9990
                    </p>
                </h2>

            </div>

        </figure>
        <figure>
            <img src="{% static 'dogs/img/entascado.jpg'%} " alt=" ">
            <div class="texto ">
                <h2>Limpiador de patas para su mascota
                    <p>
                        $7000
                    </p>
                </h2>

            </div>
            <div class="card-footer texter-center">
                <a href="#" class="btn btn-success">agregar al carro</a>
            </div>
        </figure>
        <figure>
            <img src="{% static 'dogs/img/bandana.1.jfif'%} " alt=" ">
            <div class="texto ">
                <h2>Bandanas para su mascota
                    <p>
                        $5000
                    </p>
                </h2>

            </div>

        </figure>
        <figure>
            <img src="{% static 'dogs/img/carne.jpg'%} " alt=" ">
            <div class="texto ">
                <h2>Cedula de identidad para su mascota
                    <p>
                        $2500
                    </p>
                </h2>

            </div>

        </figure>



    </div>

    


    <div class="row">
        <div class="container">
            <footer class="bg-light text-center text-black">
                <div class="container p-4 pb-0">
                    <section class="mb-3">
                        <!--  facebook -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-facebook-f"><img src="{% static 'dogs/img/facebook.png'%}" width="30px"></i></a>
                        <!-- instagram -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-instagram"><img src="{% static 'dogs/img/logoinsta.png'%}" width="30px"></i></a>
                        <!-- twitter -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-twitter"><img src="{% static 'dogs/img/twitter-logo.png'%}" width="30px"></i></a>
                </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                    Cesar Gonzalez<br> © 2022 Copyright:
                </div>
            </footer>
        </div>
</body>

</html>

dogs/templates/dogs/index.html
<!DOCTYPE html>

<html>

<head>
    {% load static %}

    <title>Pagina inicio</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'dogs/css/index.css'%} " />


</head>


<body>


    <!-- esto es la barra de tareas -->
    <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones">
            <span class="navbar-toggler-icon"></span>
        </button>

        <img src="{%static 'dogs/img/Logo.jpg'%}" width="100" height="100" alt="" />
        </a>
        <div class="collapse navbar-collapse" id="opciones">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link " href="quienessomos/">Quienes somos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="galeria/">Galeria</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="listar-producto/">Lista productos</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'agregar_producto'%}">Agregar Producto</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contactanos/">Contactanos</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="registro/">Registro</a>

                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="#"> {{ user.username }} </a>
                </li>
                <li>
                    <a href="{% url 'logout'%}"> Cerrar Sesión</a>
                </li>
                 {% else %}
                <li> <a href="{% url 'login' %} "> Iniciar Sesión </a></li>
                {% endif %}
                


            </ul>
        </div>
    </nav>


    <br>
    <h1 align="center"> Boticaria Animal</h1>
    <br />
    <div class="container-fluid">
        <div id="carousel1" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel1" data-slide-to="0" class="active"></li>
                <li data-target="#carousel1" data-slide-to="1"></li>
                <li data-target="#carousel1" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block mx-auto imagen" src="{%static 'dogs/img/pet id.jfif'%}" alt="" />
                </div>
                <div class="carousel-item">
                    <img class="d-block mx-auto imagen" src="{%static 'dogs/img/bandana.1.jfif'%}" alt="" />
                </div>
                <div class="carousel-item">
                    <img class="d-block mx-auto imagen" src="{%static 'dogs/img/carne.jpg'%}" alt="" />
                </div>
            </div>
            <a class="carousel-control-prev" href="#carousel1" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" href="#carousel1" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
        </div>
    </div>
    <br>
    <br>

    <div class="container">
        <div class="d-flex gap-3 justify-content-center align-items-center flex-row border border-dark bg-light">


            <img class="pepo" src="{%static 'dogs/img/pepo.jpg'%}" alt="imagen no disponible.">

            <p class=""> <em>
          En este sitio podrás encontrar diversos tipos de accesorios para animales, desde bandanas para perros y gatos,
          hasta sus propios identificadores únicos.

      </p></em>

        </div>
        <br>
        <div class="d-flex justify-content-center align-items-center flex-row-reverse border border-dark bg-light">
            <img class="entascado" src="{%static 'dogs/img/entascado.jpg'%}" alt="">

            <p class="p-3"> <em> NO TE QUEDES ENTASCADO!! te invitamos a que nos eches un vistazo para que no te pierdas de las diversas
          ofertas y de la asombrosa calidad de nuestros productos que tenemos para que tu bolsillo no sufra pérdidas de
          más.</p></em>

        </div>
        <br>
    </div>


    <div class="row">
        <div class="container">
            <footer class="bg-light text-center text-black">
                <div class="container p-4 pb-0">
                    <section class="mb-3">
                        <!--  facebook -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-facebook-f"><img src="{%static 'dogs/img/facebook.png'%}" width="30px"></i></a>
                        <!-- instagram -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-instagram"><img src="{%static 'dogs/img/logoinsta.png'%}" width="30px"></i></a>
                        <!-- twitter -->
                        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                class="fab fa-twitter"><img src="{%static 'dogs/img/twitter-logo.png'%}" width="30px"></i></a>
                </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                    Cesar Gonzalez<br> © 2022 Copyright:
                </div>
            </footer>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

dogs/templates/dogs/producto/agregar.html
<!DOCTYPE html>

<html>

<head>
    {% load static %}
    <title>Ingreso al sistema</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'dogs/css/agregar.css'%}">

</head>


<body>
   <nav class="navbar navbar-expand-sm navbar-light bg-white">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones">
              <span class="navbar-toggler-icon"></span>
          </button>
  
          <img src="{%static 'dogs/img/Logo.jpg'%}" width="100" height="100" alt="" />
          </a>
          <div class="collapse navbar-collapse" id="opciones">
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link " href="/">Inicio</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link " href="/quienessomos/">Quienes somos</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="/galeria/">Galeria</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="/contactanos/">Contactanos</a>
  
                  </li>
                
  
  
              </ul>
          </div>
      </nav>
  
  <br>
  <br>

{% load crispy_forms_tags %}



   
        <div class="row">
         <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
               <div class="card-body">
                  <h2>Nuevo Producto</h2>
          <form action="" method="post" enctype="multipart/form-data">
            
                {% csrf_token %}

                {{form | crispy}}
            <div class="d-flex justify-content-end">
            <input type="reset" value="Cancelar" class="btn btn-secondary">
            &nbsp;
            <input type="submit" value="Guardar" class="btn btn-secondary">
            </div>
          
          </form>
          {{mensaje}}

         </div>
   
        </div>
   
   
     </div>
   





   </div>
   <div class="container">
    <footer class="bg-light text-center text-black">
       <div class="container p-4 pb-0">
           <section class="mb-3">
               <!--  facebook -->
               <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                       class="fab fa-facebook-f"><img src="{% static 'dogs/img/facebook.png'%}" width="30px"></i></a>
               <!-- instagram -->
               <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                       class="fab fa-instagram"><img src="{%static 'dogs/img/logoinsta.png'%}" width="30px"></i></a>
               <!-- twitter -->
               <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                       class="fab fa-twitter"><img src="{% static 'dogs/img/twitter-logo.png'%}" width="30px"></i></a>
       </div>
       <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
           Cesar Gonzalez<br> © 2022 Copyright:
       </div>
       </footer>
   </div>

</body>

</html>

dogs/templates/dogs/tienda.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static%}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'dogs/css/index.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    

</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#opciones">
            <span class="navbar-toggler-icon"></span>
        </button>

        <img src="{%static 'dogs/img/Logo.jpg'%}" width="70" height="70" alt="" />
        </a>
        <div class="collapse navbar-collapse" id="opciones">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link " href="/quienessomos/">Quienes somos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/galeria/">Galeria</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/listar-producto/">Lista productos</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'agregar_producto'%}">Agregar Producto</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contactanos/">Contactanos</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/registro/">Registro</a>

                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="#"> {{ user.username }} </a>
                </li>
                <li>
                    <a href="{% url 'logout'%}"> Cerrar Sesión</a>
                </li>
                 {% else %}
                <li> <a href="{% url 'login' %} "> Iniciar Sesión </a></li>
                {% endif %}
                


            </ul>
        </div>
    </nav>
    <br>
    {% load humanize %}

<div class="container">
    <div style="float:right;">
        <p style="color:rgb(0, 0, 0);">Total:${{importe_total_carro}}</p>
        {% include "dogs/carro/widget.html" %}
    </div>
    <div class="row">
    {% for p in productos %}
    <div class="col-md-3">
        <div class="card" style="width: 100%; margin:5px 5px;">

            <img src="{{p.image.url}}" class="card-img-top">
            <div class="card-body" style="text-align: center;">
            <h7 class="card-title">{{p.nombre}}</h7>
                <p class="card-text">${{p.precio | intcomma}}</p>
            </div>
            <div class="card-footer text-center">
                <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">agregar al carro</a>
            </div>
        </div>



    </div>

    {%  endfor %}
    </div>
</div>
</body>
</html>